"""
URL helper module for IntelliHostel.
Provides centralized, robust generation of public-facing application URLs
(e.g., links included in emails sent to students and staff).
"""
import os
from typing import Optional
import backend.config as config

PRODUCTION_BASE_URL = "https://student-complaint-portal-beta.vercel.app"
LOCAL_BASE_URL = "http://127.0.0.1:5000"


def get_app_base_url() -> str:
    """
    Returns the resolved public base URL for links generated by IntelliHostel.
    Uses APP_BASE_URL as the single source of truth across all environments.

    Resolution order:
    1. Environment variable 'APP_BASE_URL' (runtime / Vercel env var override)
    2. Explicitly customized config.APP_BASE_URL (if altered in settings or mocked)
    3. Flask current_app.config['APP_BASE_URL'] (if in Flask application context)
    4. config.APP_BASE_URL (module default)
    5. Environment fallback:
       - Production (IS_PRODUCTION=True, APP_ENV=production, or VERCEL=1): PRODUCTION_BASE_URL
       - Development / Local: LOCAL_BASE_URL
    """
    is_prod = (
        getattr(config, "IS_PRODUCTION", False)
        or os.environ.get("APP_ENV", "").strip().lower() in {"production", "prod"}
        or os.environ.get("VERCEL", "").strip() in {"1", "true"}
    )

    # 1. Environment variable override (e.g. from Vercel environment or test patch)
    env_val = os.environ.get("APP_BASE_URL", "").strip().rstrip("/")
    if env_val:
        if is_prod and ("127.0.0.1" in env_val or "localhost" in env_val):
            return PRODUCTION_BASE_URL
        return env_val

    # 2. Config module attribute override (e.g. patched in unit tests)
    config_val = getattr(config, "APP_BASE_URL", "")
    if config_val:
        config_val_clean = str(config_val).strip().rstrip("/")
        # If in production, ensure no localhost leakage
        if is_prod and ("127.0.0.1" in config_val_clean or "localhost" in config_val_clean):
            return PRODUCTION_BASE_URL
        if config_val_clean:
            return config_val_clean

    # 3. Flask application context config
    try:
        from flask import current_app, has_app_context
        if has_app_context():
            app_val = current_app.config.get("APP_BASE_URL")
            if app_val and str(app_val).strip():
                clean_app_val = str(app_val).strip().rstrip("/")
                if is_prod and ("127.0.0.1" in clean_app_val or "localhost" in clean_app_val):
                    return PRODUCTION_BASE_URL
                return clean_app_val
    except Exception:
        pass

    # 4. Fallback based on environment
    return PRODUCTION_BASE_URL if is_prod else LOCAL_BASE_URL


def build_public_url(path: str = "") -> str:
    """
    Constructs a public URL using the configured APP_BASE_URL.
    Safely normalizes trailing and leading slashes to prevent double slashes.

    Example behavior:
        build_public_url("/complaint/14")
        -> https://student-complaint-portal-beta.vercel.app/complaint/14 (production)
        -> http://127.0.0.1:5000/complaint/14 (local development)

        build_public_url("complaint/14")
        -> https://student-complaint-portal-beta.vercel.app/complaint/14

        build_public_url("//complaint/14")
        -> https://student-complaint-portal-beta.vercel.app/complaint/14
    """
    base = get_app_base_url().rstrip("/")
    if not path:
        return base

    # Normalize path: strip leading slashes
    clean_path = str(path).strip().lstrip("/")
    if not clean_path:
        return base

    return f"{base}/{clean_path}"
